### ISSUE TITLE
Shows errors in 2.5.0 when bearer token is provided manually when body us nil

### ISSUE THREAD

**Issue by ash1247** [TheRakiburKhan/RKAPIService#3] opened 2022-10-17 04:55 UTC

**Comment by TheRakiburKhan** [comment] 2022-10-17 05:27
For temporary bypass please provide empty data, `Data()` as body parameter. We will fix this bug in next update.

**Comment by TheRakiburKhan** [comment] 2022-10-17 05:37
The issue is resolved in version 2.5.1

**Closed by TheRakiburKhan** 2022-10-17 05:37 UTC
